---
- name: Create container directories
  file:
    path: '{{ alertmanager_service_path }}/{{ item }}'
    state: 'directory'
    owner: 'dockremap'
    group: 'docker'
    recurse: true
  with_items:
    - 'data'
    - 'conf'

- name: Create config files
  template:
    src: '{{ item }}.j2'
    dest: '{{ alertmanager_service_path }}/conf/{{ item }}'
    owner: 'dockremap'
    group: 'docker'
  register: alertmanager_config
  with_items:
    - 'alertmanager.yml'
    - 'amtool.yml'
