---
- name: Create container directories
  file:
    path: '{{ alertmanager_cont_vol }}/{{ item }}'
    state: 'directory'
    owner: 'dockremap'
    group: 'docker'
    recurse: true
  with_items:
    - data
    - conf

- name: Create config files
  template:
    src: '{{ item }}.j2'
    dest: '{{ alertmanager_cont_vol }}/conf/{{ item }}'
    owner: 'dockremap'
    group: 'docker'
  register: alertmanager_cont_config
  with_items:
    - 'alertmanager.yml'
    - 'amtool.yml'
