---
- name: Create container directories
  file:
    path: '{{ alertmanager_service_path }}/{{ item }}'
    state: 'directory'
    owner: 'dockremap'
    group: 'docker'
    recurse: true
    mode: 0750
  with_items:
    - 'data'
    - 'conf/templates'

- name: Create amtool config file
  template:
    src:  'amtool.yml.j2'
    dest: '{{ alertmanager_service_path }}/conf/amtool.yml'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create main config file
  register: alertmanager_config_file
  copy:
    dest:    '{{ alertmanager_service_path }}/conf/alertmanager.yml'
    content: '{{ alertmanager_config | mandatory | to_nice_yaml }}'
    owner:   'dockremap'
    group:   'docker'
    mode:    0640

- name: Create template file
  copy:
    src: 'custom.tmpl'
    dest: '{{ alertmanager_service_path }}/conf/templates/custom.tmpl'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640
