---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ alertmanager_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0644

- name: Create containers
  docker_compose:
    project_src: '{{ alertmanager_service_path }}'
    pull: true
    build: false
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ alertmanager_config.changed | ternary("always", compose_recreate) }}'
